-- 12_create_raw_reference.sql
-- Layer: L1 raw_
-- Validation for this layer: sql/90_validation/91_validate_raw.sql
--
-- EXECUTED 2026-09-13. This is the statement that ran, not a description of it.
--
-- Source: Companies House Free Company Data Product, snapshot 2026-08-01.
--         7 parts, extracted from .zip to CSV (BigQuery cannot read .zip).
--         ~2.61 GB staged to GCS, europe-west2.
--
-- Autodetect is used HERE AND NOWHERE ELSE (08 §5.3): all seven parts come from
-- one publisher, one system, one day, one schema. Every spend load uses an
-- explicit schema — see 11_create_raw_spend.sql.
--
-- ===========================================================================
-- V1.5 — RESOLVED 2026-09-13. The expected figure was wrong; the load is right.
-- ===========================================================================
-- The load was reconciled against a provenance figure of 5,695,467, and closed
-- in favour of the LOADED data, on evidence:
--
--   1. 91a_reconcile_ch_per_file.sql localised the gap to ONE file: part4
--      loaded 849,999 against a census figure of 850,000. Every other part
--      matched exactly (delta 0), and the external-table total equalled the
--      managed-table total — so the load did not lose a row.
--
--   2. part4 on disk: 850,001 physical lines, 849,999 records when parsed with
--      Python csv.reader. BigQuery's parse and Python's parse agree exactly.
--      One record spans two physical lines.
--
--   3. The census could not have seen that. In provenance.csv, all seven
--      Companies House rows satisfy records_csv_parsed = row_count_raw - 1
--      EXACTLY. The column is named records_csv_parsed but for Companies House
--      it was populated from a LINE count, not a CSV parse — so it is blind to
--      embedded newlines by construction. The 62 spend rows were genuinely
--      parsed, which is why DfT correctly shows 32,524 raw against 32,515
--      records there and nothing similar appears here.
--
--   4. part1's 849,999 is real and benign. 91a returned delta 0 for it, so
--      BigQuery's parse agrees with the census figure; part1 simply has no
--      trailing newline on its final line. It is NOT a second short file.
--
-- CORRECTED per-part expectation:
--      part1 849,999 · part2 850,000 · part3 850,000 · part4 849,999
--      part5 850,000 · part6 850,000 · part7 595,468   TOTAL 5,695,466
--
-- ===========================================================================
-- AMENDED 2026-09-16 — TWO QUANTITIES, BOTH CORRECT. NOTHING ABOVE IS WRONG.
-- ===========================================================================
-- The 2026-09-13 ruling counted CSV RECORDS, and every figure in it stands:
-- part4 really does parse to 849,999 records, and 5,695,466 really is the CSV
-- record total. A local stream of part4 on 2026-09-16 reproduced 849,999
-- exactly. What the ruling did not separate is that a BigQuery table row count
-- is a different quantity:
--
--       5,695,466   CSV records across the seven parts   <- ratified, unchanged
--     -         1   part4 record #454,676 — a BLANK LINE, 0 fields.
--                   BigQuery does not materialise an empty CSV line as a row.
--     = 5,695,465   company records = COUNT(*) on this table
--
-- V1.1 and V1.5 compared a table row count against the CSV record count, so
-- they failed by one and would have done so forever. The CHECK was wrong — not
-- the load, not the source file, and not the ratified figure. The expectation
-- used by 91_validate_raw.sql is therefore 5,695,465 COMPANY RECORDS, with
-- 5,695,466 retained there as the CSV-record figure so the derivation is
-- visible rather than a bare edited number.
--
-- part4 per-part line, both quantities:  849,999 CSV records / 849,998 company
-- records. Seven-part total: 5,695,466 CSV records / 5,695,465 company records.
--
-- Corroboration, independent of the local scan: an external table over the same
-- GCS objects, anti-joined to this table on company number, returns EXACTLY ONE
-- row present in GCS and absent here — and that row carries a NULL
-- CompanyNumber and a NULL CompanyName. No company record is missing. This
-- table's metadata also shows creationTime == lastModifiedTime == 2026-09-13
-- 19:24:51 UTC with numRows 5,695,465, so it has never been modified since the
-- load and there was no load change to investigate.
--
-- THE CONTENT QUESTION IS NOW SETTLED, AND IT IS BENIGN. part4 record #454,675
-- is a LEGITIMATE quoted newline: 55 fields against a 55-field header, the
-- newline sitting inside PreviousName_10.CompanyName of company 09056746. The
-- record is intact, no fields are shifted, no company is missing, and tier-1
-- matching will not fail silently. Evidence: docs/v1_5_part4_diagnostic.md,
-- produced by scripts/06_identify_part4_merged_record.py. E-3 carries a
-- one-line note; no limitations-register entry is required.
--
-- Also verified after load, before any bucket deletion:
--   CompanyNumber data_type = STRING   PASS
--     An INTEGER inference would strip the leading zeros from numbers like
--     00445790 and fail SC/NI/OC-prefixed ones, breaking tier-1 matching
--     silently. Confirmed STRING before deletion, while a reload was still cheap.

LOAD DATA OVERWRITE `portfolio-508106.portfolio_b.raw_companies_house`
FROM FILES (
  format = 'CSV',
  -- BUCKET CONFIRMED 2026-09-14 by `gcloud storage ls`: exactly ONE bucket
  -- exists in the project — gs://portfolio-b-spend-mh2026/ — holding 7 objects,
  -- 2,803,372,555 bytes (2.61 GiB), one per Companies House part, with sizes
  -- matching the local files byte for byte. 'portfolio-b-ch-staging' does NOT
  -- exist and never did; it was an error in an execution report. No second
  -- bucket, therefore no dead storage billing.
  --
  -- NOTE the name says "spend" but the contents are the Companies House
  -- reference data. The clean spend files should go into a prefix of THIS
  -- bucket (gs://portfolio-b-spend-mh2026/clean/) rather than a second bucket,
  -- so D-P-029 condition 2 has exactly one thing to delete.
  --
  -- The URI is therefore FILE-PREFIXED, not a bare '*.csv'. As executed it read
  -- '*.csv' against a bucket that held only the 7 part files; once clean spend
  -- files share the bucket, a bare wildcard would sweep them in and this
  -- statement would stop being re-runnable. Prefixing changes nothing about
  -- what was loaded and keeps E-6 honest.
  uris = ['gs://portfolio-b-spend-mh2026/BasicCompanyData-2026-08-01-part*_7.csv'],
  skip_leading_rows = 1,
  column_name_character_map = 'V2',
  allow_jagged_rows = true,
  allow_quoted_newlines = true
);
