-- 91_validate_raw.sql
-- Layer: validation. Runs AFTER its layer, not once at the end.
-- Not yet written. Phase 3.
--
-- Note: V1.1-V1.5, all HARD. V1.1 is the foundation of E-1 — if row counts
--        do not tie to docs/provenance.csv, nothing downstream can be trusted.
