-- 45_fact_spend.sql
-- Layer: L4 reporting_
-- Not yet written. Phase 3.
-- Validation for this layer: sql/90_validation/94_validate_reporting.sql
--
-- Note: V4.1 end-to-end reconciliation lands here.
