-- 39_queue_delegated_decisions.sql
-- Layer: L3 resolved_ -- decisions the BUILDER takes under standing authorisation
--
-- EXECUTED 2026-09-22. Run after 38 and before 35.
--
-- ===========================================================================
-- THE TIERED REVIEW PROTOCOL (ruled 2026-09-22)
-- ===========================================================================
-- The review queue is tiered by the name's total transaction spend:
--   Tier A  >= GBP 10m          per-row USER decision, full evidence protocol (38)
--   Tier B  GBP 100k - < 10m    evidence batches, per-row recommendation, USER
--                               approves each batch (38)
--   Tier C  < GBP 100k          DELEGATED: the builder applies its own
--                               recommendation where the evidence fits an
--                               ESTABLISHED class, and records it HERE
--
-- WHAT A DELEGATED DECISION MAY REST ON
--   accept  -- only the corroboration / payer-records pattern established on the
--              user-decided rows (row 2: the same payer's longer spelling resolves
--              by rule to the same company; row 3: the payer's own award notices
--              state the company number)
--   reject  -- only a STRUCTURAL basis
-- Anything novel or ambiguous is escalated to the user, not decided here. New
-- evidence classes are the user's decision, not the builder's.
--
-- WHY FROZEN LITERALS, NOT A RULE THAT RUNS EVERY BUILD
-- A detector that re-ran on each build would silently decide rows that did not
-- exist when the authorisation was given -- an auto-accept by another name. So
-- each delegated decision is computed ONCE, reviewed, and written here as a
-- literal naming the exact company. The stale guard in 35 then treats it exactly
-- like a user decision: it applies only while that company is still the one on
-- offer.
--
-- PRECEDENCE. A user decision on a name ALWAYS overrides a delegated one. A user
-- reversal is recorded in 38, takes effect through the view below, and is a
-- figure-regenerating event.

CREATE OR REPLACE TABLE `portfolio-508106.portfolio_b.resolved_queue_delegated` AS
SELECT *, 'builder (Tier C)' AS decided_by
FROM UNNEST(ARRAY<STRUCT<
  supplier_name_norm       STRING,
  candidate_company_number STRING,
  decision                 STRING,
  decided_on               DATE,
  evidence_class           STRING,
  decision_note            STRING>>[
  -- DELEGATED DECISIONS -- batch 1, 2026-09-22: 55 accepts, class
  -- ACCEPT-SAME-PAYER-BRIDGE, each reviewed individually before freezing.
  STRUCT('NLA MEDIA ACCESS', '03003569', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Department for Transport pays NLA MEDIA ACCESS LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 03003569 NLA MEDIA ACCESS LIMITED. Same payer, same name core, same company. Single candidate. Tier C, GBP 94,392.00. Reviewed individually 2026-09-22.'),
  STRUCT('COPMANTHORPE CHILDCARE CENTRE', '11895873', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). City of York Council pays COPMANTHORPE CHILDCARE CENTRE LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 11895873 COPMANTHORPE CHILDCARE CENTRE LIMITED. Same payer, same name core, same company. Single candidate. Tier C, GBP 93,191.58. Reviewed individually 2026-09-22.'),
  STRUCT('NATIONAL HIGHWAYS', '09346363', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Department for Transport pays NATIONAL HIGHWAYS LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 09346363 NATIONAL HIGHWAYS LIMITED. Same payer, same name core, same company. Single candidate. Tier C, GBP 85,387.12. Reviewed individually 2026-09-22.'),
  STRUCT('VERITAS SOLICITORS', 'OC332899', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays VERITAS SOLICITORS LLP, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to OC332899 VERITAS SOLICITORS LLP. Same payer, same name core, same company. Single candidate. Tier C, GBP 83,573.53. Reviewed individually 2026-09-22.'),
  STRUCT('EXPRESS SOLICITORS', '08458462', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays EXPRESS SOLICITORS LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 08458462 EXPRESS SOLICITORS LIMITED. Same payer, same name core, same company. Single candidate. Tier C, GBP 65,923.30. Reviewed individually 2026-09-22.'),
  STRUCT('COSTAIN', '00610201', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Department for Transport pays COSTAIN LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 00610201 COSTAIN LIMITED. Same payer, same name core, same company. Single candidate. Tier C, GBP 58,309.88. Reviewed individually 2026-09-22.'),
  STRUCT('CASA ENVIRONMENTAL SERVICES', '07649903', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Bristol City Council pays CASA ENVIRONMENTAL SERVICES LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 07649903 CASA ENVIRONMENTAL SERVICES LTD. Same payer, same name core, same company. Single candidate. Tier C, GBP 57,327.00. Reviewed individually 2026-09-22.'),
  STRUCT('DRISCOLL KINGSTON AND CO', '13872283', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays DRISCOLL KINGSTON AND CO LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 13872283 DRISCOLL KINGSTON & CO LTD. Same payer, same name core, same company. Single candidate. Tier C, GBP 55,484.79. Reviewed individually 2026-09-22.'),
  STRUCT('ARENA GROUP', '02168309', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays ARENA GROUP LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 02168309 ARENA GROUP LIMITED. Same payer, same name core, same company. Single candidate. Tier C, GBP 54,713.50. Reviewed individually 2026-09-22.'),
  STRUCT('SATCHELL MORAN SOLICITORS', '09847571', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays SATCHELL MORAN SOLICITORS LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 09847571 SATCHELL MORAN SOLICITORS LIMITED. Same payer, same name core, same company. Single candidate. Tier C, GBP 46,272.13. Reviewed individually 2026-09-22.'),
  STRUCT('RISING STARS SLS', '13874983', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Bristol City Council pays RISING STARS SLS LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 13874983 RISING STARS SLS LTD. Same payer, same name core, same company. Single candidate. Tier C, GBP 37,122.00. Reviewed individually 2026-09-22.'),
  STRUCT('E ON NEXT ENERGY', '03782443', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). City of York Council pays E ON NEXT ENERGY LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 03782443 E.ON NEXT ENERGY LIMITED. Same payer, same name core, same company. Single candidate. Tier C, GBP 30,861.65. Reviewed individually 2026-09-22.'),
  STRUCT('AMELIO ENTERPRISES', '07341860', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Department for Transport pays AMELIO ENTERPRISES LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 07341860 AMELIO ENTERPRISES LIMITED. Same payer, same name core, same company. Single candidate. Tier C, GBP 30,000.00. Reviewed individually 2026-09-22.'),
  STRUCT('LITTLE FOXES FOREST SCHOOL', 'OC452105', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Bristol City Council pays LITTLE FOXES FOREST SCHOOL LLP, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to OC452105 LITTLE FOXES FOREST SCHOOL LLP. Same payer, same name core, same company. Single candidate. Tier C, GBP 29,061.24. Reviewed individually 2026-09-22.'),
  STRUCT('CBRE', '03536032', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). HM Revenue and Customs pays CBRE LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 03536032 CBRE LIMITED. Same payer, same name core, same company. Single candidate. Tier C, GBP 27,983.77. Reviewed individually 2026-09-22.'),
  STRUCT('BB HERITAGE STUDIO', '08862139', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays BB HERITAGE STUDIO LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 08862139 BB HERITAGE STUDIO LTD. Same payer, same name core, same company. Single candidate. Tier C, GBP 23,620.00. Reviewed individually 2026-09-22.'),
  STRUCT('DWF', 'OC328794', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays DWF LLP, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to OC328794 DWF LLP. Same payer, same name core, same company. Single candidate. Tier C, GBP 18,462.30. Reviewed individually 2026-09-22.'),
  STRUCT('NEWSWIFT MANAGEMENT', '07104181', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays NEWSWIFT MANAGEMENT LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 07104181 NEWSWIFT MANAGEMENT LTD. Same payer, same name core, same company. Single candidate. Tier C, GBP 17,415.00. Reviewed individually 2026-09-22.'),
  STRUCT('KLOODLE', '08497166', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays KLOODLE LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 08497166 KLOODLE LIMITED. Same payer, same name core, same company. Single candidate. Tier C, GBP 16,250.00. Reviewed individually 2026-09-22.'),
  STRUCT('MANCHESTER TUTORS', '14183845', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays MANCHESTER TUTORS LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 14183845 MANCHESTER TUTORS LTD. Same payer, same name core, same company. Single candidate. Tier C, GBP 16,195.71. Reviewed individually 2026-09-22.'),
  STRUCT('EDUCATION COMMUNITY PARTNERSHIP', '14758949', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays EDUCATION COMMUNITY PARTNERSHIP LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 14758949 THE EDUCATION COMMUNITY PARTNERSHIP LTD. Same payer, same name core, same company. Single candidate. Tier C, GBP 14,250.00. Reviewed individually 2026-09-22.'),
  STRUCT('CHESHIRE ESTATE AND LEGAL', '10370954', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays CHESHIRE ESTATE AND LEGAL LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 10370954 CHESHIRE ESTATE AND LEGAL LIMITED. Same payer, same name core, same company. Single candidate. Tier C, GBP 13,650.00. Reviewed individually 2026-09-22.'),
  STRUCT('SLS SOLICITORS', '13043393', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays SLS SOLICITORS LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 13043393 SLS SOLICITORS LIMITED. Same payer, same name core, same company. Single candidate. Tier C, GBP 10,000.00. Reviewed individually 2026-09-22.'),
  STRUCT('RYANS SOLICITORS', '08374353', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays RYANS SOLICITORS LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 08374353 RYANS SOLICITORS LIMITED. Same payer, same name core, same company. Single candidate. Tier C, GBP 9,976.68. Reviewed individually 2026-09-22.'),
  STRUCT('LITTLE ANGELS DAY NURSERY', '13852950', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays LITTLE ANGELS DAY NURSERY LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 13852950 LITTLE ANGELS DAY NURSERY LTD. Same payer, same name core, same company. Single candidate. Tier C, GBP 9,778.28. Reviewed individually 2026-09-22.'),
  STRUCT('CUSTOMER FIRST VENUE SERVICES', '08522015', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays CUSTOMER FIRST VENUE SERVICES LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 08522015 CUSTOMER FIRST VENUE SERVICES LTD. Same payer, same name core, same company. Single candidate. Tier C, GBP 8,936.00. Reviewed individually 2026-09-22.'),
  STRUCT('FORBES SOLICITORS', 'OC433300', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays FORBES SOLICITORS LLP, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to OC433300 FORBES SOLICITORS LLP. Same payer, same name core, same company. Single candidate. Tier C, GBP 8,256.00. Reviewed individually 2026-09-22.'),
  STRUCT('BARNES SOLICITORS', 'OC428641', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays BARNES SOLICITORS LLP, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to OC428641 BARNES SOLICITORS LLP. Same payer, same name core, same company. Single candidate. Tier C, GBP 7,906.81. Reviewed individually 2026-09-22.'),
  STRUCT('CLEAR LAW', 'OC308339', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays CLEAR LAW LLP, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to OC308339 CLEAR LAW LLP. Same payer, same name core, same company. Single candidate. Tier C, GBP 7,650.64. Reviewed individually 2026-09-22.'),
  STRUCT('TRADE UNION LEGAL', 'OC388189', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays TRADE UNION LEGAL LLP, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to OC388189 TRADE UNION LEGAL LLP. Same payer, same name core, same company. Single candidate. Tier C, GBP 7,556.00. Reviewed individually 2026-09-22.'),
  STRUCT('PROJEKTS MCR', 'IP29726R', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays PROJEKTS MCR LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to IP29726R PROJEKTS MCR LIMITED. Same payer, same name core, same company. Single candidate. Tier C, GBP 7,500.00. Reviewed individually 2026-09-22.'),
  STRUCT('CLEARWATER SOLICITORS', '10462199', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays CLEARWATER SOLICITORS LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 10462199 CLEARWATER SOLICITORS LIMITED. Same payer, same name core, same company. Single candidate. Tier C, GBP 6,340.00. Reviewed individually 2026-09-22.'),
  STRUCT('CROWN HOMES', '07588128', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays CROWN HOMES LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 07588128 CROWN HOMES LTD. Same payer, same name core, same company. Single candidate. Tier C, GBP 5,887.57. Reviewed individually 2026-09-22.'),
  STRUCT('NO 5 CHAMBERS', '02727465', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays NO 5 CHAMBERS LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 02727465 NO 5 CHAMBERS LIMITED. Same payer, same name core, same company. Single candidate. Tier C, GBP 4,750.00. Reviewed individually 2026-09-22.'),
  STRUCT('CALLACK CONSULTING', '15143445', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays CALLACK CONSULTING LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 15143445 CALLACK CONSULTING LIMITED. Same payer, same name core, same company. Single candidate. Tier C, GBP 3,750.00. Reviewed individually 2026-09-22.'),
  STRUCT('PROPERTY MADE TO ORDER', '11520182', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays PROPERTY MADE TO ORDER LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 11520182 PROPERTY MADE TO ORDER LTD. Same payer, same name core, same company. Single candidate. Tier C, GBP 3,750.00. Reviewed individually 2026-09-22.'),
  STRUCT('CLAIMSMITHS LAW', 'OC443644', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays CLAIMSMITHS LAW LLP, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to OC443644 CLAIMSMITHS LAW LLP. Same payer, same name core, same company. Single candidate. Tier C, GBP 3,700.00. Reviewed individually 2026-09-22.'),
  STRUCT('MJV AND CO SOLICITORS', '10042666', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays MJV AND CO SOLICITORS LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 10042666 MJV & CO SOLICITORS LTD. Same payer, same name core, same company. Single candidate. Tier C, GBP 3,100.00. Reviewed individually 2026-09-22.'),
  STRUCT('RADWEB', '06057546', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays RADWEB LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 06057546 RADWEB LTD. Same payer, same name core, same company. Single candidate. Tier C, GBP 3,080.00. Reviewed individually 2026-09-22.'),
  STRUCT('CURAE SOLICITORS', '13924238', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays CURAE SOLICITORS LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 13924238 CURAE SOLICITORS LTD. Same payer, same name core, same company. Single candidate. Tier C, GBP 2,500.00. Reviewed individually 2026-09-22.'),
  STRUCT('NEUROBOX', '10744571', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays NEUROBOX LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 10744571 NEUROBOX LIMITED. Same payer, same name core, same company. Single candidate. Tier C, GBP 2,456.00. Reviewed individually 2026-09-22.'),
  STRUCT('TRUE SOLICITORS', 'OC372714', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays TRUE SOLICITORS LLP, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to OC372714 TRUE SOLICITORS LLP. Same payer, same name core, same company. Single candidate. Tier C, GBP 2,189.77. Reviewed individually 2026-09-22.'),
  STRUCT('LITTLE YEARS NURSERY', '14019481', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). City of York Council pays LITTLE YEARS NURSERY LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 14019481 LITTLE YEARS NURSERY LTD. Same payer, same name core, same company. Single candidate. Tier C, GBP 2,080.98. Reviewed individually 2026-09-22.'),
  STRUCT('LITERACY PLANET', '06197996', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays LITERACY PLANET LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 06197996 LITERACY PLANET LIMITED. Same payer, same name core, same company. Single candidate. Tier C, GBP 1,800.00. Reviewed individually 2026-09-22.'),
  STRUCT('TOUGH FURNITURE', '03333515', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays TOUGH FURNITURE LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 03333515 TOUGH FURNITURE LTD.. Same payer, same name core, same company. Single candidate. Tier C, GBP 1,664.40. Reviewed individually 2026-09-22.'),
  STRUCT('SHARED LIVES PLUS', '04511426', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays SHARED LIVES PLUS LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 04511426 SHARED LIVES PLUS LIMITED. Same payer, same name core, same company. Single candidate. Tier C, GBP 1,379.17. Reviewed individually 2026-09-22.'),
  STRUCT('BLIND IMAGE', '12357628', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). City of York Council pays BLIND IMAGE LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 12357628 BLIND IMAGE LIMITED. Same payer, same name core, same company. Single candidate. Tier C, GBP 1,300.00. Reviewed individually 2026-09-22.'),
  STRUCT('FORESIGHT CLINICAL SERVICES', '06354163', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays FORESIGHT CLINICAL SERVICES LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 06354163 FORESIGHT CLINICAL SERVICES LIMITED. Same payer, same name core, same company. Single candidate. Tier C, GBP 1,133.50. Reviewed individually 2026-09-22.'),
  STRUCT('FARRER AND CO', 'OC323570', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays FARRER AND CO LLP, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to OC323570 FARRER & CO LLP. Same payer, same name core, same company. Single candidate. Tier C, GBP 1,000.00. Reviewed individually 2026-09-22.'),
  STRUCT('LET ME MANCHESTER', '09537000', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays LET ME MANCHESTER LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 09537000 LET ME MANCHESTER LIMITED. Same payer, same name core, same company. Single candidate. Tier C, GBP 925.00. Reviewed individually 2026-09-22.'),
  STRUCT('PROFORMA ARTS', '12277616', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays PROFORMA ARTS LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 12277616 PROFORMA ARTS LTD. Same payer, same name core, same company. Single candidate. Tier C, GBP 916.59. Reviewed individually 2026-09-22.'),
  STRUCT('STEPHENSONS SOLICITORS', 'OC322962', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays STEPHENSONS SOLICITORS LLP, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to OC322962 STEPHENSONS SOLICITORS LLP. Same payer, same name core, same company. Single candidate. Tier C, GBP 912.00. Reviewed individually 2026-09-22.'),
  STRUCT('BUNZL UK', '02902454', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). City of York Council pays BUNZL UK LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 02902454 BUNZL UK LIMITED. Same payer, same name core, same company. Single candidate. Tier C, GBP 644.62. Reviewed individually 2026-09-22.'),
  STRUCT('IRISH TOWN MANCHESTER', '13781331', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays IRISH TOWN MANCHESTER LTD, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to 13781331 IRISH TOWN MANCHESTER LIMITED. Same payer, same name core, same company. Single candidate. Tier C, GBP 616.20. Reviewed individually 2026-09-22.'),
  STRUCT('RUSSELL AND RUSSELL SOLICITORS', 'OC420972', 'accepted', DATE '2026-09-22', 'ACCEPT-SAME-PAYER-BRIDGE', 'ACCEPT-SAME-PAYER-BRIDGE (the row-2 class). Manchester City Council pays RUSSELL AND RUSSELL SOLICITORS LLP, a spelling with the same suffix-free name that resolves BY RULE (tier 2 or 3) to OC420972 RUSSELL & RUSSELL SOLICITORS LLP. Same payer, same name core, same company. Single candidate. Tier C, GBP 616.00. Reviewed individually 2026-09-22.')
]);

-- One view of every decision in force. 35, 37 and 93 read this, never the two
-- tables directly, so precedence is defined in exactly one place.
CREATE OR REPLACE VIEW `portfolio-508106.portfolio_b.resolved_queue_all_decisions` AS
SELECT supplier_name_norm, candidate_company_number, decision, decided_on,
       'user_review' AS evidence_class, decision_note, decided_by
FROM `portfolio-508106.portfolio_b.resolved_queue_decisions`
UNION ALL
SELECT supplier_name_norm, candidate_company_number, decision, decided_on,
       evidence_class, decision_note, decided_by
FROM `portfolio-508106.portfolio_b.resolved_queue_delegated`
WHERE supplier_name_norm NOT IN (
  SELECT supplier_name_norm FROM `portfolio-508106.portfolio_b.resolved_queue_decisions`);
