#!/usr/bin/env python3
"""
Portfolio B — Pre-load transformation (08-transformation-guidelines.md §2.5)

===============================================================================
PREREQUISITES
===============================================================================
Run from        repository root
Python          3.8+, standard library only. No pip install needed.

READS (repo-relative):
    docs/provenance.csv        69 rows x 18 cols   ** NOT IN A FRESH CLONE **
    data/raw/*.csv             62 files            ** NOT IN A FRESH CLONE **

    Both are build inputs that live in the Obsidian vault, outside version
    control — data/raw/ is gitignored and provenance.csv is not generated by
    any script here. Put them in place with:

        python scripts/00_setup_inputs.py

WRITES:
    data/clean/*.csv           62 files            GITIGNORED — verify with
                                                   git check-ignore -v data/clean/x.csv
    docs/validation_report.md  the s2.6 report     TRACKED — this is evidence

This script refuses to start if any input is missing, and names the command
that fixes it. It does not create, guess at or silently skip inputs.

===============================================================================
USAGE
===============================================================================
    python scripts/05_preload_clean.py                 clean + validate
    python scripts/05_preload_clean.py --validate-only  re-run s2.6 only
    python scripts/05_preload_clean.py --check          preflight only, no work

DESIGN NOTES
  - stdlib only. No pandas. B is a SQL portfolio; Python here is acquisition
    and preparation plumbing, not analysis (charter §4).
  - The csv module parses quoted fields containing commas AND newlines, which
    is what the 9 DfT multi-line records require. A line-based read splits them.
  - Nothing is cast, cleaned or reformatted. Dates, amounts and supplier names
    pass through byte-for-byte as text. Layer 2 transforms them in SQL, where
    the raw value stays visible beside the parsed one.
  - An unrecognised header HALTS the run. A publisher that changed format is a
    human decision, not something to guess at.
"""

from __future__ import annotations
import argparse, csv, sys
from pathlib import Path

csv.field_size_limit(min(sys.maxsize, 2**31 - 1))

ROOT       = Path(__file__).resolve().parents[1]
RAW        = ROOT / "data" / "raw"
CLEAN      = ROOT / "data" / "clean"
PROVENANCE = ROOT / "docs" / "provenance.csv"

EXPECTED_FILES   = 62
EXPECTED_RECORDS = 364_835          # §2.6 check 2 — NOT 364,844 (see docstring below)

META = ["_source_file", "_source_url", "_retrieved_at", "_period", "_row_num"]

# ---------------------------------------------------------------------------
# §2.3 canonical header maps. Keys are matched after .strip().
# Every documented variant is listed explicitly.
# ---------------------------------------------------------------------------
PUBLISHERS = {
    "Bristol City Council": {
        "table": "raw_spend_bristol",
        "columns": ["body", "body_name", "supplier_name_src", "amount_src",
                    "payment_date_src", "transaction_number",
                    "description_1", "description_2", "description_3"],
        "map": {
            "Body": "body",
            "Body Name": "body_name",
            "Name": "supplier_name_src",
            "amount": "amount_src",
            "Amount": "amount_src",
            "Pay Date": "payment_date_src",
            "Transaction Number": "transaction_number",
            "Description 1": "description_1",
            "Description 2": "description_2",
            "Description 3": "description_3",
        },
    },
    "City of York Council": {
        "table": "raw_spend_york",
        "columns": ["body_name", "directorate", "department", "service_plan",
                    "supplier_name_src", "payment_date_src", "transaction_number",
                    "card_transaction", "amount_src", "irrecoverable_vat_src",
                    "subjective_group", "subjective_subgroup", "subjective_detail"],
        "map": {
            "Organisation_Name": "body_name",
            "Directorate": "directorate",
            "Department": "department",
            "Service_Plan": "service_plan",
            "Creditor_Name": "supplier_name_src",
            "Payment_Date": "payment_date_src",
            "Transaction_No": "transaction_number",
            "Card_Transaction": "card_transaction",
            "Net_Amount": "amount_src",
            "Irrecoverable_VAT": "irrecoverable_vat_src",
            "Subjective_Group": "subjective_group",
            "Subjective_Subgroup": "subjective_subgroup",
            "Subjective_Detail": "subjective_detail",
        },
    },
    "Department for Transport": {
        "table": "raw_spend_dft",
        "columns": ["department_family", "entity", "payment_date_src",
                    "expense_type", "expense_area", "supplier_name_src",
                    "transaction_number", "description_1", "amount_src",
                    "supplier_postcode_src"],
        "map": {
            "Department Family": "department_family",
            "Entity": "entity",
            "Date": "payment_date_src",
            "Expense Type": "expense_type",
            "Expense Area": "expense_area",
            "Supplier": "supplier_name_src",
            "Transaction No": "transaction_number",
            "Transaction Number": "transaction_number",
            "Item Text": "description_1",
            "£": "amount_src",                 # the header is literally " £ "
            "Postal Code": "supplier_postcode_src",
        },
    },
    "HM Revenue and Customs": {
        "table": "raw_spend_hmrc",
        "columns": ["department_family", "entity", "payment_date_src",
                    "expense_type", "expense_area", "supplier_name_src",
                    "transaction_number", "amount_src", "description_1",
                    "supplier_postcode_src", "supplier_type", "contract_number",
                    "project_code", "expenditure_type"],
        "map": {
            "Department family": "department_family",
            "Entity": "entity",
            "Date": "payment_date_src",
            "Expense type": "expense_type",
            "Expense area": "expense_area",
            "Supplier": "supplier_name_src",
            "Transaction number": "transaction_number",
            "Amount": "amount_src",
            "Description": "description_1",
            "Supplier Postcode": "supplier_postcode_src",
            "Supplier Type": "supplier_type",
            "Contract Number": "contract_number",
            "Project Code": "project_code",
            "Expenditure Type": "expenditure_type",
        },
    },
    "Manchester City Council": {
        "table": "raw_spend_manchester",
        "columns": ["body_name", "business_area", "service_area", "expense_type",
                    "payment_date_src", "transaction_number", "supplier_name_src",
                    "amount_src"],
        "map": {
            "Body Name": "body_name",
            "Business Area and Description": "business_area",
            "Service Area": "service_area",
            "Expenses type": "expense_type",
            "Invoice Payment Date": "payment_date_src",
            "Transaction Number": "transaction_number",
            "Supplier Name": "supplier_name_src",
            "Net Amount": "amount_src",
        },
    },
    "Ministry of Justice": {
        "table": "raw_spend_moj",
        "columns": ["department_family", "entity", "payment_date_src",
                    "expense_type", "expense_area", "supplier_name_src",
                    "transaction_number", "amount_src", "description_1"],
        "map": {
            "Department family": "department_family",
            "Entity": "entity",
            "Date": "payment_date_src",
            "Expense type": "expense_type",
            "Expense area": "expense_area",
            "Supplier": "supplier_name_src",
            "Transaction number": "transaction_number",
            "Amount": "amount_src",
            "Description": "description_1",
        },
    },
}


def load_provenance() -> dict:
    """local_file -> provenance row. §2.5 step 5 matches on local_file."""
    if not PROVENANCE.exists():
        sys.exit(f"HALT: {PROVENANCE} not found. It supplies _source_url, "
                 f"_retrieved_at and _period. Copy it from the acquisition record.")
    with PROVENANCE.open(encoding="utf-8-sig", newline="") as fh:
        rows = list(csv.DictReader(fh))
    needed = {"local_file", "publisher", "source_url", "retrieval_date", "period_covered"}
    missing = needed - set(rows[0].keys())
    if missing:
        sys.exit(f"HALT: provenance.csv is missing column(s): {sorted(missing)}")
    return {r["local_file"]: r for r in rows}


def detect_encoding(path: Path) -> str:
    """R5 — CP1252 unless the file opens with a UTF-8 BOM."""
    with path.open("rb") as fh:
        return "utf-8-sig" if fh.read(3) == b"\xef\xbb\xbf" else "cp1252"


def clean_one(src: Path, prov: dict) -> dict:
    row = prov.get(src.name)
    if row is None:
        sys.exit(f"HALT: {src.name} has no provenance.csv row (matched on local_file). "
                 f"Every raw file must be traceable or _source_url, _retrieved_at "
                 f"and _period cannot be populated.")

    pub = row["publisher"]
    if pub not in PUBLISHERS:
        sys.exit(f"HALT: {src.name} names publisher '{pub}', which has no header map.")
    spec = PUBLISHERS[pub]

    enc = detect_encoding(src)
    with src.open(encoding=enc, newline="") as fh:
        reader = csv.reader(fh)
        try:
            header = next(reader)
        except StopIteration:
            sys.exit(f"HALT: {src.name} is empty.")

        # --- R6: map every header, or stop -----------------------------------
        positions, dropped_unnamed, loose = {}, 0, []
        unnamed_idx: list[int] = []
        for idx, raw_h in enumerate(header):
            h = raw_h.strip()
            if h == "":
                dropped_unnamed += 1          # MOJ padding — §2.3, counted not silent
                unnamed_idx.append(idx)       # verified empty in EVERY row below
                continue
            canon = spec["map"].get(h)
            if canon is None:                 # last resort: case-insensitive, REPORTED
                for k, v in spec["map"].items():
                    if k.lower() == h.lower():
                        canon, _ = v, loose.append(f"{raw_h!r}->{k!r}")
                        break
            if canon is None:
                sys.exit(
                    f"HALT: unrecognised header in {src.name}\n"
                    f"       column {idx}: {raw_h!r}\n"
                    f"       publisher: {pub}\n"
                    f"       This means the publisher changed format. A human must "
                    f"look and extend the §2.3 map — do not guess.")
            positions[canon] = idx

        # --- Rewrite ----------------------------------------------------------
        # LAYER 1 DROPS NOTHING (08 §5.2). Blank padding rows are WRITTEN, not
        # skipped. They are removed at Layer 2, in SQL, where the decision is
        # visible in a query rather than buried in a Python filter.
        #
        # Two things depend on this and both are load-bearing:
        #   * §2.6 check 2 expects 364,835 — records_csv_parsed, which INCLUDES
        #     the 12,221 padding rows. Skipping them yields 352,614 (records_real).
        #   * _row_num must equal the record's ordinal position in the SOURCE
        #     file, or E-1's "traceable to a physical line in a named file" is
        #     broken. Padding is not always trailing: in Ministry_of_Justice
        #     2025-01 ten blanks sit before the last real record, and in
        #     Manchester 2024-04 two do. Skipping them renumbers everything after.
        out_cols = spec["columns"] + META
        CLEAN.mkdir(parents=True, exist_ok=True)
        dst, n, blanks = CLEAN / src.name, 0, 0
        with dst.open("w", encoding="utf-8", newline="") as out:
            w = csv.writer(out, quoting=csv.QUOTE_ALL, lineterminator="\n")
            w.writerow(out_cols)
            for rec in reader:
                n += 1
                # §2.3 permits discarding unnamed trailing columns ONLY because
                # they have "no name and no values in any row". Verify the second
                # half of that claim rather than trusting it.
                for idx in unnamed_idx:
                    if idx < len(rec) and rec[idx].strip():
                        sys.exit(
                            f"HALT: {src.name} record {n} carries data in an "
                            f"UNNAMED column {idx}: {rec[idx]!r}\n"
                            f"       §2.3 discards unnamed columns because they are "
                            f"empty padding. This one is not.\n"
                            f"       Do not guess at its meaning — a human must "
                            f"extend the §2.3 map.")
                if not any(f.strip() for f in rec):
                    blanks += 1               # counted and KEPT, per 08 §5.2
                vals = [rec[positions[c]] if c in positions and positions[c] < len(rec)
                        else "" for c in spec["columns"]]
                vals += [src.name, row["source_url"], row["retrieval_date"],
                         row["period_covered"], str(n)]
                w.writerow(vals)

    return {"file": src.name, "publisher": pub, "encoding": enc, "records": n,
            "blanks": blanks, "expected_blanks": int(row.get("blank_padding_rows") or 0),
            "unnamed_dropped": dropped_unnamed, "loose_header_matches": loose,
            "expected": int(row.get("records_csv_parsed") or 0)}


def validate() -> int:
    """§2.6 — all four must pass."""
    files = sorted(CLEAN.glob("*.csv"))
    print("\n" + "=" * 74 + "\n§2.6 VALIDATION\n" + "=" * 74)

    n_files = len(files)
    c1 = n_files == EXPECTED_FILES
    print(f"1. File count in data/clean/           {n_files:>10,}   expect {EXPECTED_FILES:>10,}   "
          f"{'PASS' if c1 else 'FAIL'}")

    total = 0
    for f in files:
        with f.open(encoding="utf-8", newline="") as fh:
            total += sum(1 for _ in csv.reader(fh)) - 1
    c2 = total == EXPECTED_RECORDS
    print(f"2. Sum of data rows                    {total:>10,}   expect {EXPECTED_RECORDS:>10,}   "
          f"{'PASS' if c2 else 'FAIL'}")
    if total == 364_844:
        print("   ^ 364,844 means the reader used lines instead of CSV parsing.")
        print("     The 9 DfT records with embedded newlines are now split in half.")
    if total == 352_614:
        print("   ^ 352,614 is records_real — the pre-load DROPPED the 12,221 blank")
        print("     padding rows. 08 §5.2: Layer 1 drops nothing; padding goes at L2.")
        print("     It also breaks _row_num wherever padding is not trailing.")

    # Check 3 — see the note below. A raw byte scan is the WRONG test.
    bad = []
    for f in files:
        try:
            f.read_text(encoding="utf-8")
        except UnicodeDecodeError as e:
            bad.append(f"{f.name}: {e}")
    c3 = not bad
    print(f"3. Files that fail a strict UTF-8 decode {len(bad):>8,}   expect {0:>10,}   "
          f"{'PASS' if c3 else 'FAIL'}")
    for b in bad[:5]:
        print(f"     {b}")

    sigs = {}
    for f in files:
        with f.open(encoding="utf-8", newline="") as fh:
            sigs.setdefault(tuple(next(csv.reader(fh))), []).append(f.name)
    c4 = len(sigs) == 6
    print(f"4. Distinct header signatures          {len(sigs):>10,}   expect {6:>10,}   "
          f"{'PASS' if c4 else 'FAIL'}")
    for sig, names in sigs.items():
        print(f"     {len(names):>2} files · {len(sig):>2} cols · {sig[0]}...{sig[-1]}")

    ok = c1 and c2 and c3 and c4
    print("\n" + ("ALL FOUR PASS — clean files are ready for §5.1 load."
                  if ok else "AT LEAST ONE CHECK FAILED — do not load."))
    return 0 if ok else 1


def preflight(validate_only: bool) -> list[str]:
    """Return a list of human-readable problems. Empty list means ready.

    Checked BEFORE any work starts. A missing input is reported with the
    command that fixes it, never worked around.
    """
    problems: list[str] = []

    if not PROVENANCE.exists():
        problems.append(
            f"MISSING  {PROVENANCE.relative_to(ROOT)}\n"
            f"         This file is NOT in the repository. It is acquisition\n"
            f"         evidence held in the Obsidian vault at\n"
            f"         06_ACTIVE_BUILD/portfolio-b/data/provenance.csv\n"
            f"         FIX:  python scripts/00_setup_inputs.py")

    if not validate_only:
        if not RAW.exists():
            problems.append(
                f"MISSING  {RAW.relative_to(ROOT)}/  (directory does not exist)\n"
                f"         FIX:  python scripts/00_setup_inputs.py")
        else:
            n = len(list(RAW.glob("*.csv")))
            if n != EXPECTED_FILES:
                problems.append(
                    f"WRONG COUNT  {RAW.relative_to(ROOT)}/ holds {n} .csv files, "
                    f"expected {EXPECTED_FILES}\n"
                    f"         data/raw/ is gitignored, so a fresh clone is empty.\n"
                    f"         08 §1.2: a missing file makes every downstream count wrong.\n"
                    f"         FIX:  python scripts/00_setup_inputs.py")

    if not CLEAN.exists():
        # Recoverable — but say so rather than creating it silently.
        problems.append(
            f"MISSING  {CLEAN.relative_to(ROOT)}/  (output directory)\n"
            f"         08 §2.5 step 6 writes the 62 clean files here.\n"
            f"         FIX:  python scripts/00_setup_inputs.py\n"
            f"         THEN CONFIRM it is ignored — this repository is public:\n"
            f"               git check-ignore -v data/clean/x.csv")

    return problems


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--validate-only", action="store_true")
    ap.add_argument("--check", action="store_true",
                    help="run the prerequisite check and exit")
    args = ap.parse_args()

    problems = preflight(args.validate_only)
    if problems:
        print("PREREQUISITES NOT MET — nothing has been read or written.\n")
        for p in problems:
            print(p + "\n")
        return 1
    if args.check:
        print(f"Prerequisites OK.")
        print(f"  {PROVENANCE.relative_to(ROOT)}   present")
        print(f"  {RAW.relative_to(ROOT)}/         "
              f"{len(list(RAW.glob('*.csv')))} files")
        print(f"  {CLEAN.relative_to(ROOT)}/       present")
        return 0

    if not args.validate_only:
        prov = load_provenance()
        srcs = sorted(p for p in RAW.glob("*.csv"))
        if not srcs:
            sys.exit(f"HALT: no .csv files in {RAW}")
        print(f"Cleaning {len(srcs)} files from {RAW}\n")
        print(f"{'file':<45}{'enc':<10}{'records':>10}{'vs prov':>10}{'blank':>8}{'vs prov':>9}")
        print("-" * 92)
        results, drift, pad_drift = [], [], []
        for s in srcs:
            r = clean_one(s, prov)
            results.append(r)
            delta = r["records"] - r["expected"] if r["expected"] else 0
            if delta:
                drift.append(r)
            bdelta = r["blanks"] - r["expected_blanks"]
            if bdelta:
                pad_drift.append(r)
            print(f"{r['file']:<45}{r['encoding']:<10}{r['records']:>10,}"
                  f"{('  ' + ('=' if not delta else f'{delta:+d}')):>10}"
                  f"{r['blanks']:>8,}"
                  f"{('  ' + ('=' if not bdelta else f'{bdelta:+d}')):>9}")

        unnamed = sum(r["unnamed_dropped"] for r in results)
        loose = [(r["file"], m) for r in results for m in r["loose_header_matches"]]
        print(f"\nUnnamed trailing columns discarded (MOJ padding, §2.3): {unnamed}")
        if loose:
            print(f"Headers matched only case-insensitively — REVIEW THESE:")
            for f, m in loose:
                print(f"   {f}: {m}")
        if drift:
            print(f"\n{len(drift)} file(s) differ from provenance.records_csv_parsed:")
            for r in drift:
                print(f"   {r['file']}: got {r['records']:,}, provenance says {r['expected']:,}")
        else:
            print(f"\nAll {len(srcs)} files match provenance.records_csv_parsed exactly.")

        # Free extra control: provenance carries blank_padding_rows per file, so
        # the padding kept at L1 can be reconciled the same way the records are.
        tot_blank = sum(r["blanks"] for r in results)
        exp_blank = sum(r["expected_blanks"] for r in results)
        print(f"Blank padding rows KEPT at L1: {tot_blank:,}  "
              f"(provenance.blank_padding_rows: {exp_blank:,})  "
              f"{'=' if tot_blank == exp_blank else 'MISMATCH'}")
        if pad_drift:
            for r in pad_drift:
                print(f"   {r['file']}: kept {r['blanks']:,}, provenance says "
                      f"{r['expected_blanks']:,}")

    return validate()


if __name__ == "__main__":
    sys.exit(main())
